//! Deterministic (seeded) synthetic-scenario generator for the EKF differential-conformance
//! harness. Emits the line-oriented scenario grammar shared by the C++ `ekf_replay` tool and
//! `examples/ekf_replay.rs`, covering the boundary cases of the port plan: delay-gate
//! rejection, NaN/Inf injection, Mahalanobis rejection, yaw ±π wrap, dt=0 and >10 s clamp,
//! jump-back in time, queue-aging × smoothing bursts, yaw-bias on/off, and the
//! zero-velocity-twist covariance override.
//!
//! Usage: `gen_scenarios <output_dir>`

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::as_conversions,
    clippy::let_underscore_must_use,
    clippy::type_complexity,
    clippy::too_many_lines,
    clippy::cast_lossless,
    reason = "test code (conformance harness example)"
)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use realtime_ekf_localizer::tf2_math::quaternion_from_rpy;

const SEC: i64 = 1_000_000_000;
const TICK_NS: i64 = 20_000_000; // 50 Hz

/// xorshift64* — deterministic, dependency-free.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(seed.max(1))
    }
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    /// Uniform in [0, 1).
    fn f64(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }
    /// Uniform in [-1, 1).
    fn sym(&mut self) -> f64 {
        2.0 * self.f64() - 1.0
    }
}

struct Scenario {
    out: String,
}

impl Scenario {
    fn new() -> Self {
        Self {
            out: String::from("# generated by gen_scenarios.rs (deterministic; do not edit)\n"),
        }
    }

    fn param(&mut self, key: &str, value: f64) {
        let _ = writeln!(self.out, "param {key} {value}");
    }

    fn cov_line(cov: &[f64; 36]) -> String {
        cov.iter()
            .map(|c| format!("{c:.17e}"))
            .collect::<Vec<_>>()
            .join(" ")
    }

    fn init(&mut self, stamp_ns: i64, x: f64, y: f64, z: f64, yaw: f64, cov: &[f64; 36]) {
        let q = quaternion_from_rpy(0.0, 0.0, yaw);
        let _ = writeln!(
            self.out,
            "init {stamp_ns} {x:.17e} {y:.17e} {z:.17e} {:.17e} {:.17e} {:.17e} {:.17e} {}",
            q[0],
            q[1],
            q[2],
            q[3],
            Self::cov_line(cov)
        );
    }

    #[expect(
        clippy::too_many_arguments,
        reason = "scenario line mirrors the grammar"
    )]
    fn pose_rpy(
        &mut self,
        stamp_ns: i64,
        x: f64,
        y: f64,
        z: f64,
        roll: f64,
        pitch: f64,
        yaw: f64,
        cov: &[f64; 36],
    ) {
        let q = quaternion_from_rpy(roll, pitch, yaw);
        self.pose_quat(stamp_ns, x, y, z, q, cov);
    }

    fn pose_quat(&mut self, stamp_ns: i64, x: f64, y: f64, z: f64, q: [f64; 4], cov: &[f64; 36]) {
        let _ = writeln!(
            self.out,
            "pose {stamp_ns} {x:.17e} {y:.17e} {z:.17e} {:.17e} {:.17e} {:.17e} {:.17e} {}",
            q[0],
            q[1],
            q[2],
            q[3],
            Self::cov_line(cov)
        );
    }

    fn twist(&mut self, stamp_ns: i64, vx: f64, wz: f64, cov: &[f64; 36]) {
        let _ = writeln!(
            self.out,
            "twist {stamp_ns} {vx:.17e} 0 0 0 0 {wz:.17e} {}",
            Self::cov_line(cov)
        );
    }

    /// Twist with full angular velocity (exercises the roll/pitch delay compensation).
    fn twist_full(&mut self, stamp_ns: i64, linear: [f64; 3], angular: [f64; 3], cov: &[f64; 36]) {
        let _ = writeln!(
            self.out,
            "twist {stamp_ns} {:.17e} {:.17e} {:.17e} {:.17e} {:.17e} {:.17e} {}",
            linear[0],
            linear[1],
            linear[2],
            angular[0],
            angular[1],
            angular[2],
            Self::cov_line(cov)
        );
    }

    fn tick(&mut self, now_ns: i64) {
        let _ = writeln!(self.out, "tick {now_ns}");
    }

    fn write(self, dir: &Path, name: &str) {
        fs::write(dir.join(name), self.out).unwrap();
        println!("wrote {name}");
    }
}

fn pose_cov() -> [f64; 36] {
    let mut c = [0.0_f64; 36];
    c[0] = 0.0225; // X_X
    c[7] = 0.0225; // Y_Y
    c[14] = 0.09; // Z_Z
    c[21] = 0.001; // ROLL
    c[28] = 0.001; // PITCH
    c[35] = 0.0064; // YAW
    c
}

fn twist_cov() -> [f64; 36] {
    let mut c = [0.0_f64; 36];
    c[0] = 0.01;
    c[35] = 0.005;
    c
}

/// Common driving scenario: poses at 10 Hz (delayed), twists at 100 Hz, ticks at 50 Hz.
fn drive(
    name: &str,
    dir: &Path,
    seed: u64,
    n_ticks: usize,
    wz: f64,
    inject: &dyn Fn(&mut Scenario, usize, i64, &mut Rng, &mut (f64, f64, f64)),
    params: &[(&str, f64)],
) {
    let mut rng = Rng::new(seed);
    let mut s = Scenario::new();
    for (k, v) in params {
        s.param(k, *v);
    }
    let t0 = 1000 * SEC;
    let cov = pose_cov();
    let tcov = twist_cov();

    // State used to synthesize consistent measurements: x, y, yaw.
    let vx = 8.0;
    let mut truth = (5000.0, -3000.0, 3.10); // yaw near +pi to exercise wrap when turning
    s.init(t0, truth.0, truth.1, 0.4, truth.2, &cov);

    let mut now = t0;
    for i in 0..n_ticks {
        now += TICK_NS;
        let dt = TICK_NS as f64 / 1e9;
        truth.2 = libm::atan2(libm::sin(truth.2 + wz * dt), libm::cos(truth.2 + wz * dt));
        truth.0 += vx * libm::cos(truth.2) * dt;
        truth.1 += vx * libm::sin(truth.2) * dt;

        // 100 Hz twists: two per tick, stamped a little in the past.
        for k in 0..2 {
            let st = now - 10_000_000 * (2 - k) - 2_000_000;
            s.twist_full(
                st,
                [vx + 0.05 * rng.sym(), 0.0, 0.0],
                [0.002 * rng.sym(), 0.002 * rng.sym(), wz + 0.01 * rng.sym()],
                &tcov,
            );
        }
        // 10 Hz poses: every 5th tick, delay 40-80 ms.
        if i % 5 == 0 {
            let delay = 40_000_000 + (rng.f64() * 40e6) as i64;
            let st = now - delay;
            s.pose_rpy(
                st,
                truth.0 + 0.05 * rng.sym(),
                truth.1 + 0.05 * rng.sym(),
                0.4 + 0.02 * rng.sym(),
                0.005 * rng.sym(),
                0.005 * rng.sym(),
                truth.2 + 0.01 * rng.sym(),
                &cov,
            );
        }
        inject(&mut s, i, now, &mut rng, &mut truth);
        s.tick(now);
    }
    s.write(dir, name);
}

fn main() {
    let args: Vec<String> = env::args().collect();
    assert_eq!(args.len(), 2, "usage: gen_scenarios <output_dir>");
    let dir = Path::new(&args[1]);
    fs::create_dir_all(dir).unwrap();

    let no_inject = |_: &mut Scenario, _: usize, _: i64, _: &mut Rng, _: &mut (f64, f64, f64)| {};

    // 1. Straight drive baseline.
    drive("straight.scn", dir, 1, 300, 0.0, &no_inject, &[]);

    // 2. Turn crossing the ±π yaw wrap repeatedly.
    drive("yaw_wrap.scn", dir, 2, 300, 0.4, &no_inject, &[]);

    // 3. Delay-gate rejections: occasional poses stamped far in the past.
    drive(
        "delay_gate.scn",
        dir,
        3,
        300,
        0.1,
        &|s, i, now, _rng, truth| {
            if i % 40 == 7 {
                // ~5 s stale: beyond the 1 s delay table (50 steps x 20 ms).
                s.pose_rpy(
                    now - 5 * SEC,
                    truth.0,
                    truth.1,
                    0.4,
                    0.0,
                    0.0,
                    truth.2,
                    &pose_cov(),
                );
            }
            if i % 40 == 27 {
                // Stale twist: exercises the twist delay-gate rejection.
                s.twist(now - 5 * SEC, 8.0, 0.1, &twist_cov());
            }
        },
        &[],
    );

    // 4. NaN/Inf injection into pose x, pose quaternion, twist vx.
    drive(
        "nan_inject.scn",
        dir,
        4,
        200,
        0.05,
        &|s, i, now, _rng, truth| {
            let cov = pose_cov();
            let tcov = twist_cov();
            match i {
                50 => s.pose_rpy(
                    now - 30_000_000,
                    f64::NAN,
                    truth.1,
                    0.4,
                    0.0,
                    0.0,
                    truth.2,
                    &cov,
                ),
                90 => s.pose_quat(
                    now - 30_000_000,
                    truth.0,
                    truth.1,
                    0.4,
                    [f64::NAN, 0.0, 0.0, 1.0],
                    &cov,
                ),
                130 => s.twist(now - 5_000_000, f64::NAN, 0.05, &tcov),
                170 => s.pose_rpy(
                    now - 30_000_000,
                    truth.0,
                    f64::INFINITY,
                    0.4,
                    0.0,
                    0.0,
                    truth.2,
                    &cov,
                ),
                _ => {}
            }
        },
        &[],
    );

    // 5. Mahalanobis rejections: tight gates + far measurements.
    drive(
        "mahalanobis.scn",
        dir,
        5,
        300,
        0.1,
        &|s, i, now, _rng, truth| {
            if i % 30 == 11 {
                s.pose_rpy(
                    now - 30_000_000,
                    truth.0 + 40.0,
                    truth.1 - 40.0,
                    0.4,
                    0.0,
                    0.0,
                    truth.2 + 0.5,
                    &pose_cov(),
                );
            }
            if i % 45 == 17 {
                s.twist(now - 5_000_000, 30.0, -3.0, &twist_cov());
            }
        },
        &[("pose_gate_dist", 3.0), ("twist_gate_dist", 2.0)],
    );

    // 6. dt = 0 tick (repeated now) and tiny dt.
    drive(
        "dt_zero.scn",
        dir,
        6,
        150,
        0.05,
        &|s, i, now, _rng, _truth| {
            if i % 25 == 13 {
                s.tick(now); // duplicate tick timestamp: measured dt == 0 on the next tick line
            }
        },
        &[],
    );

    // 7. Giant dt: a >10 s gap between ticks triggers the dt clamp.
    {
        let mut s = Scenario::new();
        let t0 = 1000 * SEC;
        let cov = pose_cov();
        let tcov = twist_cov();
        s.init(t0, 100.0, 200.0, 0.3, 0.7, &cov);
        let mut now = t0;
        for _ in 0..20 {
            now += TICK_NS;
            s.twist(now - 5_000_000, 2.0, 0.05, &tcov);
            s.tick(now);
        }
        now += 15 * SEC; // 15 s stall -> dt clamped to 10 s
        s.twist(now - 5_000_000, 2.0, 0.05, &tcov);
        s.tick(now);
        for _ in 0..40 {
            now += TICK_NS;
            s.pose_rpy(now - 30_000_000, 100.5, 200.5, 0.3, 0.0, 0.0, 0.72, &cov);
            s.tick(now);
        }
        s.write(dir, "dt_clamp.scn");
    }

    // 8. Jump back in time (warn-only branch: no dt update, no accumulation).
    {
        let mut s = Scenario::new();
        let t0 = 1000 * SEC;
        let cov = pose_cov();
        let tcov = twist_cov();
        s.init(t0, -50.0, 75.0, 0.2, -2.0, &cov);
        let mut now = t0;
        for i in 0..120 {
            now += TICK_NS;
            s.twist(now - 5_000_000, 3.0, -0.1, &tcov);
            if i == 60 {
                s.tick(now - 500_000_000); // 0.5 s in the past
            }
            if i % 5 == 2 {
                s.pose_rpy(now - 40_000_000, -50.0, 75.0, 0.2, 0.0, 0.0, -2.0, &cov);
            }
            s.tick(now);
        }
        s.write(dir, "time_jump_back.scn");
    }

    // 9. Queue aging x smoothing: bursts exceeding max queue sizes.
    drive(
        "queue_burst.scn",
        dir,
        9,
        200,
        0.05,
        &|s, i, now, rng, truth| {
            if i % 20 == 5 {
                // Burst of 8 poses (max_pose_queue_size = 5) and 5 twists (max = 2).
                for k in 0..8 {
                    let st = now - 20_000_000 - (k as i64) * 3_000_000;
                    s.pose_rpy(
                        st,
                        truth.0 + 0.02 * rng.sym(),
                        truth.1 + 0.02 * rng.sym(),
                        0.4,
                        0.0,
                        0.0,
                        truth.2,
                        &pose_cov(),
                    );
                }
                for k in 0..5 {
                    s.twist(
                        now - 4_000_000 - (k as i64) * 2_000_000,
                        8.0,
                        0.05,
                        &twist_cov(),
                    );
                }
            }
        },
        &[],
    );

    // 10. Yaw-bias estimation disabled.
    drive(
        "yaw_bias_off.scn",
        dir,
        10,
        250,
        0.15,
        &no_inject,
        &[("enable_yaw_bias_estimation", 0.0)],
    );

    // 12. Non-positive-definite measurement covariance: S = C P C^T + R fails the LLT inside
    // updateWithDelay; the C++ discards that bool (state unchanged, still traced as accepted).
    drive(
        "llt_reject.scn",
        dir,
        12,
        150,
        0.05,
        &|s, i, now, _rng, truth| {
            if i % 30 == 9 {
                let mut bad = pose_cov();
                bad[0] = -1.0; // negative-definite R block
                bad[7] = -1.0;
                bad[35] = -1.0;
                s.pose_rpy(
                    now - 30_000_000,
                    truth.0,
                    truth.1,
                    0.4,
                    0.0,
                    0.0,
                    truth.2,
                    &bad,
                );
            }
        },
        &[],
    );

    // 11. Zero-velocity twists below threshold_observable_velocity_mps (covariance override).
    drive(
        "slow_velocity.scn",
        dir,
        11,
        200,
        0.0,
        &|s, i, now, _rng, _truth| {
            if i % 10 < 5 {
                s.twist(now - 5_000_000, 0.05, 0.001, &twist_cov()); // below 0.2 threshold
            }
        },
        &[("threshold_observable_velocity_mps", 0.2)],
    );
}
